# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: MailingService
    - run: npm run build --if-present
      working-directory: MailingService
    - run: npm test
      working-directory: MailingService
    - run: HEROKU_API_KEY='095bb12b-f496-4ad8-b2c7-1b5f33d38116' heroku run ls --app mailing-service-app
    - run: git remote add heroku https://git.heroku.com/mailing-service-app.git
    - run: git show-ref
    - run: git add .
    - run: git config --global user.email "angeloakuhwa@gmail.com"
    - run: git config --global user.name "ANGELO AKUHWA"
    - run: git commit -m "first"
    - run: git push -u heroku main
